export const MOUSE_EVENT_ADD = 'MOUSE_EVENT_ADD'
export const MOUSE_EVENT_RESET = 'MOUSE_EVENT_RESET'
export const MOUSE_EVENT_LAST_HOVERED_OBJECT = 'MOUSE_EVENT_LAST_HOVERED_OBJECT'

export const SCENE_ADD = 'SCENE_ADD'
export const SCENE_SET_CURRENT = 'SCENE_SET_CURRENT'
export const SCENE_SET_COMPLETE = 'SCENE_SET_COMPLETE'

